heat_template_version: ocata

parameters:
  key_name:
    type: string
  flavor:
    type: string
  image:
    type: string
  private_net:
    type: string
  security_groups:
    type: string
  volume_size:
    type: number
  slave_name:
    type: string

resources:

  server:
    type: OS::Nova::Server
    properties:
      name: {get_param: slave_name}
      image:
        get_param: image
      flavor:
        get_param: flavor
      key_name:
        get_param: key_name
      networks:
      - port: {get_resource: server_port}
      user_data_format: SOFTWARE_CONFIG
      block_device_mapping: [{"volume_id": { get_resource: volume_storage },
                              "delete_on_termination": true,
                              "device_name": "vda"}]
  volume_storage:
    type: OS::Cinder::Volume
    properties:
      size: {get_param: volume_size}
      image: {get_param: image}

  server_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net }
      security_groups:
        - { get_param: security_groups }

outputs:
  slave_ip:
    value:
      get_attr: [server, first_address]
  slave_id:
    value:
      get_resource: server
