heat_template_version: rocky

parameters:
  server:
    type: string
  HiveMysqlUser:
    type: string
    default: 'root'
  HiveMysqlPassword:
    type: string
    default: 'root'

resources:
  HiveSoftwareConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      inputs:
        - name: hive_site_xml
        - name: hive_mycnf
      config: {get_file: ../ansible/hive.yaml}

  HiveSoftwareDeployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      input_values:
        hive_site_xml: {get_file: ../ansible/templates/hive-site.j2.xml}
        hive_mycnf: {get_file: ../ansible/templates/hive_mycnf.j2}
        mysql_user: {get_param: HiveMysqlUser}
        mysql_password: {get_param: HiveMysqlPassword}
      config:
        get_resource: HiveSoftwareConfig
      server:
        get_param: server

outputs:
  stdout:
    description: Hive config stdout
    value:
      get_attr: [HiveSoftwareDeployment, deploy_stdout]
  stderr:
    description: Hive config stderr
    value:
      get_attr: [HiveSoftwareDeployment, deploy_stderr]
