heat_template_version: rocky

parameters:
  server:
    type: string

resources:
  HiveSoftwareConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/bash
        tar -xf /opt/apache-hive-3.1.2-bin.tar.gz -c /opt
        ln -s /opt/pache-hive-3.1.2-bin /opt/hive
        echo export HIVE_HOME=/opt/hive >> /root/.profile
        echo export HIVE_CONF_DIR=/opt/hive/conf >> /root/.profile
        echo export PATH=$SPARK_HOME/bin:$PATH
        /opt/spark/sbin/stop-master.sh
        /opt/spark/sbin/start-master.sh
  HiveSoftwareDeployment:
    type: OS::Heat::SoftwareDeployment
    config:
      get_resource: HiveSoftwareConfig
    server:
      get_param: server

outputs:
  result:
    description: Hive config result
    value:
      get_attr: [HiveSoftwareDeployment, result]
  stdout:
    description: Hive config stdout
    value:
      get_attr: [HiveSoftwareDeployment, stdout]
  stderr:
    description: Hive config stderr
    value:
      get_attr: [HiveSoftwareDeployment, stderr]
