heat_template_version: rocky

parameters:
  server:
    type: string

resources:
  MahoutSoftwareConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: {get_file: scripts/config_mahout.sh}
  MahoutSoftwareDeployment:
    type: OS::Heat::SoftwareDeployment
    config:
      get_resource: MahoutSoftwareConfig
    server:
      get_param: server

outputs:
  result:
    description: Mahout config result
    value:
      get_attr: [MahoutSoftwareDeployment, result]
  stdout:
    description: Mahout config stdout
    value:
      get_attr: [MahoutSoftwareDeployment, stdout]
  stderr:
    description: Mahout config stderr
    value:
      get_attr: [MahoutSoftwareDeployment, stderr]
