heat_template_version: rocky

parameters:
  server:
    type: string

resources:
  SparkSoftwareConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      config: {get_file: ansible/spark.yaml}
  SparkSoftwareDeployment:
    type: OS::Heat::SoftwareDeployment
    config:
      get_resource: SparkSoftwareConfig
    server:
      get_param: server

outputs:
  stdout:
    description: Spark config stdout
    value:
      get_attr: [SparkSoftwareDeployment, deploy_stdout]
  stderr:
    description: Spark config stderr
    value:
      get_attr: [SparkSoftwareDeployment, deploy_stderr]
