---
- hosts: localhost
  connection: local
  tasks:
    - name: Add master to /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: "{{ master_ip }}"
        line: "{{ master_ip }} hadoop-master"

    - name: Add a slave to /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: "{{ slave_ip }}"
        line: "{{ slave_ip }} {{ slave_hostname }}"

    - copy:
        content: "{{ core_site_xml }}" # templates/core-site.j2.xml
        dest: "/opt/hadoop/etc/hadoop/core-site.xml"
    - copy:
        content: "{{ hdfs_site_xml }}" # templates/hdfs-site.j2.xml
        dest: "/opt/hadoop/etc/hadoop/hdfs-site.xml"
    - copy:
        content: "{{ mapred_site_xml }}" # templates/mapred-site.j2.xml
        dest: "/opt/hadoop/etc/hadoop/mapred-site.xml"
    - copy:
        content: "{{ yarn_site_xml }}" # templates/yarn-site.j2.xml
        dest: "/opt/hadoop/etc/hadoop/yarn-site.xml"
    - name: Remove localhost in file
      lineinfile:
        path: /opt/hadoop/etc/hadoop/workers
        regexp: "localhost"
        state: absent
    - name: Add workers to file
      lineinfile:
        path: /opt/hadoop/etc/hadoop/workers
        regexp: "{{ slave_hostname }}"
        line: "{{ slave_hostname }}"

