---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Generate ssh key
      shell: |
        if [ ! -f /root/.ssh/id_rsa.pub ];then
          echo -e "\n" | ssh-keygen -t rsa -N "" > /dev/null
        fi
        cat /root/.ssh/id_rsa.pub
      register: keypair

    - name: Heat outputs id_rsa_pub
      lineinfile:
        create: yes
        path: "{{ heat_outputs_path }}.id_rsa_pub"
        line: "{{ keypair.stdout }}"

    - name: Add key for ssh nopass
      authorized_key:
        user: root
        state: present
        key: "{{ keypair.stdout }}"

