---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Format hadoop
      shell: |
        source /root/.bashrc
        hdfs namenode -format

    - name: Stop all
      shell: |
        /opt/hadoop-3.1.2/sbin/stop-all.sh
        source /root/.bashrc

    - name: Start all
      shell: |
        source /root/.bashrc
        /opt/hadoop-3.1.2/sbin/start-all.sh
