---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Format hadoop
      shell: |
        source /root/.bashrc
        if [ ! -f "/root/data/nameNode/current/VERSION" ]; then
          hdfs namenode -format
        fi

    - name: Start Hadoop
      shell: |
        source /root/.bashrc
        RESULT=$(/opt/hadoop-3.1.2/sbin/start-all.sh 2>&1)
        egrep "ERROR|error" <<< "$RESULT"
        if [ $? -eq 0 ]; then
          echo -e "$RESULT"
          echo "HDFS Start with no error"
          exit 0
        fi



