---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Add key for ssh nopass
      authorized_key:
        user: root
        state: present
        key: "{{ id_rsa_pub }}"
